package dev.alonx3.ktnacontrol.protocol

import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * The preset addresses are generated with [Address] arithmetic instead of being written out,
 * so these tests check the generated bytes against the layout the spec describes — not
 * against the same formula that produced them.
 */
class KatanaAddressesTest {

    @Test
    fun `generates the eight preset name addresses`() {
        assertEquals(8, KatanaAddresses.PRESET_NAMES.size)

        // Expected layout per CLAUDE.md §5: 10 01 00 00 … 10 08 00 00.
        KatanaAddresses.PRESET_NAMES.forEachIndexed { index, address ->
            assertEquals("10 %02X 00 00".format(index + 1), address.toString())
        }
    }

    @Test
    fun `each preset name address only differs in the second byte`() {
        KatanaAddresses.PRESET_NAMES.forEachIndexed { index, address ->
            assertEquals(0x10, address.byte0)
            assertEquals(index + 1, address.byte1)
            assertEquals(0x00, address.byte2)
            assertEquals(0x00, address.byte3)
        }
    }

    @Test
    fun `presetName counts from one like the front panel`() {
        assertEquals(KatanaAddresses.FIRST_PRESET_NAME, KatanaAddresses.presetName(1))
        assertEquals("10 08 00 00", KatanaAddresses.presetName(8).toString())
    }

    @Test
    fun `presetName rejects numbers outside 1 to 8`() {
        assertThrows(IllegalArgumentException::class.java) { KatanaAddresses.presetName(0) }
        assertThrows(IllegalArgumentException::class.java) { KatanaAddresses.presetName(9) }
    }

    @Test
    fun `the generated addresses build the queries traced in HOW md`() {
        // Strongest check: the bytes on the wire must match the reference traces exactly.
        assertEquals(
            "F0 41 00 00 00 00 33 11 10 01 00 00 00 00 00 10 5F F7",
            RolandSysEx.get(KatanaAddresses.presetName(1), KatanaAddresses.PRESET_NAME_SIZE)
                .joinToString(" ") { "%02X".format(it.toInt() and 0xFF) },
        )
        assertEquals(
            "F0 41 00 00 00 00 33 11 10 02 00 00 00 00 00 10 5E F7",
            RolandSysEx.get(KatanaAddresses.presetName(2), KatanaAddresses.PRESET_NAME_SIZE)
                .joinToString(" ") { "%02X".format(it.toInt() and 0xFF) },
        )
    }
}
